/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get OAuth2 configuration for client-side authentication
         * @description Returns the Cognito OAuth2 configuration values needed for the frontend to perform the PKCE authorization code flow.
         */
        get: operations["AuthConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates an internal user record using the Cognito identity from the JWT.
         *     If the phone number matches an existing shell user (no auth_subject), links the Cognito identity to that user.
         *     The Authorization header must contain a valid JWT, but this endpoint is in the auth allowlist
         *     so the standard auth middleware is skipped — the handler validates the JWT itself.
         */
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview an invite without consuming it
         * @description Returns invite metadata (sender name, masked recipient phone, expiry) for display
         *     before the recipient completes Cognito signup. Does not consume the token.
         *     Public endpoint — no authentication required.
         */
        get: operations["GetInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's accounts */
        get: operations["ListMyAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new account
         * @description Creates a new account and adds the authenticated user as a member.
         */
        post: operations["CreateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/wallet/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account wallet balances */
        get: operations["GetAccountWalletBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account payment methods */
        get: operations["GetAccountPaymentMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account activity */
        get: operations["GetAccountActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a transfer or payment request
         * @description Creates either a direct payment (type=direct) or a payment request (type=request).
         *
         *     **Direct Payment Flow (type=direct):**
         *     1. Authenticated user initiates payment
         *     2. Payment executes immediately if no contract required
         *     3. If contract required, creates pending payment awaiting signature
         *
         *     **Payment Request Flow (type=request):**
         *     1. Authenticated user creates payment request
         *     2. Creates pending payment with status=pending
         *     3. Payer must later accept via /payment-requests/{id}/accept
         *
         *     **Authorization:**
         *     - Direct: User must have access to source account (payer)
         *     - Request: User must have access to destination account (recipient)
         */
        post: operations["CreateTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transfer details */
        get: operations["GetTransferDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deposits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get external deposit details */
        get: operations["GetDepositDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-requests/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a payment request
         * @description Accepts a payment request and executes the transfer
         */
        post: operations["AcceptPaymentRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get contracts for an account */
        get: operations["GetAccountContracts"];
        put?: never;
        /** Create a contract */
        post: operations["CreateContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAccountDocuments"];
        put?: never;
        post: operations["CreateDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a contract by ID */
        get: operations["GetContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contract-requirements/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a contract requirement
         * @description Marks a contract requirement as accepted by the user
         */
        post: operations["AcceptContractRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/wallet/payment-requests/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate payment link
         * @description Creates a Stripe checkout session for payment requests
         */
        post: operations["GeneratePaymentLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quickbooks/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handle QuickBooks OAuth2 callback
         * @description Handles the Intuit OAuth2 redirect. On success, stores the connection and redirects
         *     to `<frontendBaseURL>/settings?qb_connected=true`. On failure, redirects to
         *     `<frontendBaseURL>/settings?qb_error=<code>`.
         *
         *     This endpoint is in the auth allowlist — no JWT is required because it is
         *     invoked by a browser redirect from Intuit, not by an authenticated API client.
         *     The account is recovered from the CSRF state token, not from a path parameter.
         */
        get: operations["QuickBooksCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quickbooks/{accountId}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate QuickBooks OAuth2 connection
         * @description Creates a CSRF state token and issues a 302 redirect to the Intuit authorization URL.
         *
         *     **Full OAuth2 flow:**
         *     1. Frontend navigates the browser to this endpoint.
         *     2. Server redirects to Intuit's authorization page.
         *     3. User grants (or denies) consent on Intuit's site.
         *     4. Intuit redirects the browser to `/api/v1/quickbooks/callback`.
         *     5. On success, the server stores the connection and redirects to `<frontendBaseURL>/settings?qb_connected=true`.
         *     6. On failure, the server redirects to `<frontendBaseURL>/settings?qb_error=<code>`.
         *
         *     **Possible `qb_error` codes the frontend may receive:**
         *     - `access_denied` — user cancelled or denied consent on Intuit's page
         *     - `state_expired` — the CSRF state token expired before the user completed the flow (>10 min); prompt to retry
         *     - `invalid_state` — state token was not found or already used
         *     - `invalid_callback` — the callback was missing required parameters
         *     - `token_exchange_failed` — Intuit rejected the authorization code exchange
         *     - `store_failed` — tokens were exchanged successfully but could not be saved
         *     - `integration_disabled` — QuickBooks is not configured on this server
         *     - `intuit_error` — Intuit returned an unrecognised error; see Intuit's OAuth2 docs
         */
        get: operations["QuickBooksConnect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quickbooks/{accountId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get QuickBooks connection status for an account
         * @description Returns whether the account has an active QuickBooks connection. Includes refresh token expiry so the frontend can warn the user before re-auth is required.
         */
        get: operations["QuickBooksStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quickbooks/{accountId}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect QuickBooks from an account
         * @description Revokes the OAuth tokens with Intuit and soft-deletes the stored connection.
         */
        post: operations["QuickBooksDisconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/moov/onboarding-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a Moov onboarding context token for this account
         * @description Issues a short-lived Moov access token scoped for client-side onboarding or
         *     Drops usage. If the account already has a linked Moov account ID, an access
         *     token scoped to that account is returned. Otherwise an account-creation token
         *     is returned so the client can create a new Moov account.
         *     Token-issuance only — this endpoint never writes linkage or modifies account state.
         */
        post: operations["GetMoovOnboardingContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/moov/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create and link a Moov account for this account
         * @description Server-authoritative endpoint that calls Moov to create a new business account
         *     using the backend's trusted facilitator credentials, then links the resulting
         *     Moov account ID to the Maple account. No client-supplied Moov ID is required.
         *     Idempotent — if the account already has a linked Moov account, returns 200 with
         *     the existing Moov account ID.
         */
        post: operations["CreateMoovAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moov/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available Moov industry options
         * @description Returns the list of industry slugs, display names, and default MCCs that can be submitted via the CreateMoovAccount endpoint.
         */
        get: operations["ListMoovIndustries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Error message */
            error: string;
        };
        MessageResponse: {
            /** @description Success message */
            message: string;
        };
        MoovCapability: {
            /** @description Status of the Moov capability */
            status: string;
        };
        Account: {
            /** @description Account ID */
            id: string;
            /** @description Associated Moov account ID */
            moovAccountID: string;
            /** @description Map of capability names to their status */
            capabilities: {
                [key: string]: components["schemas"]["MoovCapability"];
            };
            /** @description Whether the account has all required capabilities enabled for payments */
            ready: boolean;
        };
        ListMyAccountsResponse: {
            data: components["schemas"]["Account"][];
        };
        CreateAccountRequest: {
            /** @description Name of the account (company name) */
            name: string;
        };
        CreateAccountResponse: {
            /** @description Created account ID */
            id: string;
        };
        GetMyBalancesResponse: {
            /**
             * Format: double
             * @description Available balance
             */
            available: number;
            /**
             * Format: double
             * @description Pending payments amount
             */
            pendingPayments: number;
        };
        PaymentMethod: {
            /** @description Payment method ID */
            id: string;
            /** @description Bank name */
            bankName?: string;
            /** @description Last 4 digits of account number */
            last4?: string;
            /**
             * @description Type of payment method
             * @enum {string}
             */
            type: "bank_account" | "platform_account";
            /**
             * Format: double
             * @description Current balance
             */
            balance?: number;
        };
        GetMyPaymentMethodsResponse: {
            data: components["schemas"]["PaymentMethod"][];
        };
        Transfer: {
            /** @description Transfer ID */
            id: string;
            /**
             * Format: double
             * @description Transfer amount
             */
            amount: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /** @description Transfer note */
            note: string;
            /** @description Transfer status */
            status: string;
            /** @description Name of the other party in the transfer */
            otherPartyName: string;
            /** @description Transfer type (inbound/outbound) */
            type: string;
        };
        CreateTransferRequest: {
            /**
             * @description Transfer type determines payment flow:
             *     - "direct": Authenticated user pays immediately (push payment)
             *       - User is the payer, must provide paymentMethodID
             *       - Specify recipient via recipientPhone OR destinationAccountID
             *     - "request": Authenticated user requests payment (pull payment)
             *       - User is the recipient, creates a payment request
             *       - Specify payer via payerPhone OR sourceAccountID
             *       - Payer must later accept the request via /payment-requests/{id}/accept
             * @enum {string}
             */
            type: "direct" | "request";
            /** @description Phone number of payment recipient (for type="direct" - alternative to destinationAccountID) */
            recipientPhone?: string;
            /** @description Account ID that will receive the payment (for type="direct" - alternative to recipientPhone) */
            destinationAccountID?: string;
            /** @description Phone number of payer (for type="request" - alternative to sourceAccountID) */
            payerPhone?: string;
            /** @description Account ID that will send the payment (for type="request" - alternative to payerPhone) */
            sourceAccountID?: string;
            /** @description Payment method to use (required for type="direct", not used for type="request") */
            paymentMethodID?: string;
            /**
             * Format: double
             * @description Amount to transfer
             */
            amount: number;
            /** @description Optional note for the transfer */
            note?: string;
            documentIDs?: string[];
            /** @description Optional contract ID if contract signature required */
            contractID?: string;
        };
        AcceptPaymentRequestRequest: {
            /** @description Payment method to use for accepting the payment request */
            paymentMethodID: string;
        };
        ContractAgreement: {
            /**
             * Format: date-time
             * @description Timestamp when contract was agreed to
             */
            agreedToAt: string;
            /** @description Name of person who agreed */
            agreedToByName: string;
        } | null;
        ContractRequirement: {
            /** @description Contract requirement ID */
            contractRequirementID: string;
            /** @description Contract ID */
            contractID: string;
            /** @description Contract version ID */
            contractVersionID: string;
            /** @description Contract content text */
            contractContent: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            lastUpdatedAt: string;
            contractAgreement?: components["schemas"]["ContractAgreement"];
        };
        GetMyTransactionResponse: {
            /** @description Transfer ID */
            id: string;
            /**
             * Format: double
             * @description Transfer amount
             */
            amount: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Completion timestamp
             */
            completedAt?: string | null;
            /** @description Transfer note */
            note: string;
            /** @description Transfer status */
            status: string;
            /** @description Name of the other party */
            otherPartyName: string;
            /** @description Transfer type */
            type: string;
            /** @description Associated contract requirements */
            contractRequirements: components["schemas"]["ContractRequirement"][];
            /** @description Payment method display name */
            paymentMethod?: string;
        };
        Contract: {
            /** @description Contract ID */
            id: string;
            /** @description Contract title */
            title: string;
            /** @description ID of the latest contract version */
            latest_version_id: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
            /** @description Presigned URL to download the contract content */
            download_url: string;
        };
        GetAccountContractsResponse: {
            contracts: components["schemas"]["Contract"][];
        };
        CreateContractRequest: {
            /** @description Contract content text */
            contractContent: string;
            /** @description Title of the contract */
            contractTitle: string;
        };
        CreateContractResponse: {
            /** @description Created contract ID */
            id: string;
        };
        Document: {
            id: string;
            /** @enum {string} */
            document_type: "contract" | "invoice" | "photo" | "w9";
            title: string;
            latest_version_id: string;
            /** Format: date-time */
            updated_at: string;
            download_url: string;
        };
        GetAccountDocumentsResponse: {
            documents: components["schemas"]["Document"][];
        };
        CreateDocumentRequest: {
            /**
             * @description Type of document (use POST /accounts/{id}/contracts for contracts)
             * @enum {string}
             */
            documentType: "invoice" | "photo" | "w9";
            title: string;
            /** @description MIME type (application/pdf, image/jpeg, image/png, etc.) */
            contentType: string;
            /** @description Base64-encoded file content */
            content: string;
        };
        CreateDocumentResponse: {
            /** @description Created document ID */
            id: string;
        };
        SpikeRequest: {
            /**
             * Format: double
             * @description Payment amount
             */
            amount: number;
            /** @description Payment note/description */
            note: string;
        };
        GeneratePaymentLinkResponse: {
            /**
             * Format: uri
             * @description Stripe checkout session URL
             */
            link: string;
        };
        AuthConfigResponse: {
            /** @description Cognito App Client ID */
            clientId: string;
            /** @description Cognito hosted UI base domain (e.g. https://myapp.auth.us-west-2.amazoncognito.com) */
            domain: string;
            /** @description OAuth2 redirect URI configured for this client */
            redirectUri: string;
            /** @description OAuth2 token exchange endpoint */
            tokenEndpoint: string;
            /** @description OAuth2 authorization endpoint */
            authorizeEndpoint: string;
            /** @description Cognito logout endpoint */
            logoutEndpoint: string;
        };
        RegisterRequest: {
            /** @description User's first name */
            firstName: string;
            /** @description User's last name */
            lastName: string;
            /** @description Single-use invite token from registration SMS link */
            inviteToken?: string;
        };
        RegisterResponse: {
            /** @description User ID */
            id: string;
            /** @description User's first name */
            firstName: string;
            /** @description User's last name */
            lastName: string;
            /** @description User's phone number */
            phone: string;
        };
        InvitePreviewResponse: {
            /** @description Name of the account that sent the payment */
            senderName: string;
            /** @description Masked recipient phone — last 4 digits only (e.g. "****1234") */
            recipientPhone: string;
            /** Format: date-time */
            expiresAt: string;
            expired: boolean;
        };
        CreateMoovAccountRequest: {
            /** @description Legal name of the business as registered */
            legalBusinessName: string;
            /** @description Moov business type (e.g. llc, soleProprietorship, corporation) */
            businessType: string;
            /**
             * Format: email
             * @description Business contact email address
             */
            email: string;
            phone: {
                /** @description Phone number digits (no formatting) */
                number: string;
                /** @description E.164 country code without the plus sign (e.g. "1") */
                countryCode?: string;
            };
            address: {
                addressLine1: string;
                addressLine2?: string;
                city: string;
                stateOrProvince: string;
                postalCode: string;
                country: string;
            };
            /** @description Moov industry slug (use GET /moov/industries to list options) */
            industry: string;
            /**
             * Format: uri
             * @description Business website URL (website or description required)
             */
            website?: string;
            /** @description Business description (website or description required) */
            description?: string;
            taxId: {
                ein: {
                    /** @description EIN in format XX-XXXXXXX or XXXXXXXXX */
                    number: string;
                };
            };
            /** @description Optional customer support contact information */
            customerSupport?: {
                phone?: {
                    number?: string;
                    countryCode?: string;
                };
                /** Format: email */
                email?: string;
                /** Format: uri */
                website?: string;
                address?: {
                    addressLine1?: string;
                    addressLine2?: string;
                    city?: string;
                    stateOrProvince?: string;
                    postalCode?: string;
                    country?: string;
                };
            };
        };
        CreateMoovAccountResponse: {
            /** @description The Moov account ID that was created and linked to this account */
            moovAccountID: string;
        };
        MoovIndustry: {
            /** @description Moov industry slug identifier */
            slug: string;
            /** @description Human-readable display name for this industry */
            display: string;
            /** @description Default Merchant Category Code (MCC) for this industry */
            defaultMcc: string;
        };
        ListMoovIndustriesResponse: {
            data: components["schemas"]["MoovIndustry"][];
        };
        MoovOnboardingContextResponse: {
            /** @description Short-lived Moov access token for client-side onboarding or Drop usage */
            token: string;
            /** @description Number of seconds until the token expires */
            expiresIn: number;
        };
        QuickBooksStatusResponse: {
            /** @description Whether the account has an active QuickBooks connection */
            connected: boolean;
            /** @description QuickBooks company/realm ID (present when connected=true) */
            realm_id?: string;
            /**
             * Format: date-time
             * @description When the refresh token expires (present when connected=true)
             */
            refresh_token_expires_at?: string | null;
        };
    };
    responses: never;
    parameters: {
        /** @description Account ID */
        AccountIDPath: string;
        /** @description Transfer ID */
        TransferIDPath: string;
        /** @description Moov transfer ID for an external deposit */
        DepositIDPath: string;
        /** @description Contract Requirement ID */
        ContractRequirementIDPath: string;
        /** @description Document ID */
        DocumentIDPath: string;
        /** @description Contract ID */
        ContractIDPath: string;
        /** @description Account ID */
        QuickBooksAccountIDPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auth configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigResponse"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created or linked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Missing required fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Phone number taken or auth subject already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite found and valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewResponse"];
                };
            };
            /** @description Invite not found or expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListMyAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMyAccountsResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAccountResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetAccountWalletBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMyBalancesResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetAccountPaymentMethods: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMyPaymentMethodsResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetAccountActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Transfer"][];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransferRequest"];
            };
        };
        responses: {
            /** @description Transfer or pending payment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetTransferDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transfer ID */
                id: components["parameters"]["TransferIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMyTransactionResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Transfer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetDepositDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Moov transfer ID for an external deposit */
                id: components["parameters"]["DepositIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMyTransactionResponse"];
                };
            };
            /** @description Deposit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AcceptPaymentRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transfer ID */
                id: components["parameters"]["TransferIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptPaymentRequestRequest"];
            };
        };
        responses: {
            /** @description Payment request accepted and transferred */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Transfer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetAccountContracts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAccountContractsResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContractRequest"];
            };
        };
        responses: {
            /** @description Contract created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateContractResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetAccountDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAccountDocumentsResponse"];
                };
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description Document created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDocumentResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                id: components["parameters"]["DocumentIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contract ID */
                id: components["parameters"]["ContractIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Contract not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AcceptContractRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contract Requirement ID */
                id: components["parameters"]["ContractRequirementIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract requirement accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GeneratePaymentLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpikeRequest"];
            };
        };
        responses: {
            /** @description Payment link generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratePaymentLinkResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    QuickBooksCallback: {
        parameters: {
            query?: {
                /** @description Error code returned by Intuit (present when user denies consent) */
                error?: string;
                /** @description Authorization code from Intuit */
                code?: string;
                /** @description CSRF state token created by the connect endpoint */
                state?: string;
                /** @description QuickBooks company/realm ID */
                realmId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to frontend with success or error query params */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuickBooksConnect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                accountId: components["parameters"]["QuickBooksAccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Intuit authorization page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account not found or user does not have access */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description QuickBooks integration not enabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    QuickBooksStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                accountId: components["parameters"]["QuickBooksAccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description QuickBooks connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickBooksStatusResponse"];
                };
            };
            /** @description Account not found or user does not have access */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    QuickBooksDisconnect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                accountId: components["parameters"]["QuickBooksAccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description QuickBooks disconnected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Account not found, user does not have access, or no active connection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description QuickBooks integration not enabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetMoovOnboardingContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moov token issued successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoovOnboardingContextResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — user is not a member of this account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateMoovAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: components["parameters"]["AccountIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMoovAccountRequest"];
            };
        };
        responses: {
            /** @description Moov account already linked (idempotent) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMoovAccountResponse"];
                };
            };
            /** @description Moov account created and linked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMoovAccountResponse"];
                };
            };
            /** @description Bad request — validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — user is not a member of this account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListMoovIndustries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Moov industry options */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMoovIndustriesResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
