import {
  SpotlightActionData,
  SpotlightActionGroupData,
} from "@mantine/spotlight";
import {
  UserMultiple02Icon,
  BankIcon,
  Message01Icon,
  Logout02Icon,
  DashboardCircleIcon,
  PlusSignIcon,
  ArrowUp02Icon,
  ArrowDown02Icon,
  ArrowLeftRightIcon,
  UserIcon,
  PencilEdit01Icon,
} from "hugeicons-react";
import { AppRouterInstance } from "next/dist/shared/lib/app-router-context.shared-runtime";
import { logout } from "@/app/auth/logout/actions";

export const getSpotlightActions = (
  router: AppRouterInstance
): (SpotlightActionGroupData | SpotlightActionData)[] => [
  {
    group: "Navigation",
    actions: [
      {
        id: "dashboard",
        label: "Dashboard",
        description: "View your account summary and recent activity",
        keywords: [
          "home",
          "main",
          "overview",
          "activity",
          "transactions",
          "summary",
          "feed",
          "history",
        ],
        onClick: () => router.push("/dashboard"),
        leftSection: <DashboardCircleIcon size={24} />,
      },
      {
        id: "contacts",
        label: "Contacts",
        description: "View and manage your contacts",
        keywords: [
          "people",
          "customers",
          "clients",
          "vendors",
          "address book",
          "directory",
          "friends",
          "recipients",
        ],
        onClick: () => window.dispatchEvent(new CustomEvent("open-contacts")),
        leftSection: <UserMultiple02Icon size={24} />,
      },
      {
        id: "banks",
        label: "Bank Accounts",
        description: "Manage your connected bank accounts",
        keywords: [
          "connect",
          "plaid",
          "funding",
          "payment methods",
          "financial",
          "accounts",
          "link bank",
          "manage banks",
        ],
        onClick: () => window.dispatchEvent(new CustomEvent("open-banks")),
        leftSection: <BankIcon size={24} />,
      },
    ],
  },
  {
    group: "Actions",
    actions: [
      {
        id: "deposit",
        label: "Deposit",
        description: "Add money to your Holler account",
        keywords: [
          "add funds",
          "load money",
          "deposit funds",
          "transfer in",
          "add cash",
          "fund account",
        ],
        onClick: () => window.dispatchEvent(new CustomEvent("open-deposit")),
        leftSection: <PlusSignIcon size={24} />,
      },
      {
        id: "send",
        label: "Send",
        description: "Send a payment to a contact",
        keywords: [
          "send money",
          "pay",
          "make payment",
          "transfer out",
          "send funds",
          "payout",
        ],
        onClick: () => window.dispatchEvent(new CustomEvent("open-send")),
        leftSection: <ArrowUp02Icon size={24} />,
      },
      {
        id: "request",
        label: "Request",
        description: "Request a payment from a contact",
        keywords: [
          "request money",
          "ask for payment",
          "bill",
          "invoice",
          "charge",
          "collect funds",
        ],
        onClick: () => window.dispatchEvent(new CustomEvent("open-request")),
        leftSection: <ArrowDown02Icon size={24} />,
      },
      {
        id: "transfer",
        label: "Transfer",
        description: "Transfer funds between your accounts",
        keywords: [
          "move money",
          "internal transfer",
          "between accounts",
          "self transfer",
          "move funds",
        ],
        onClick: () => window.dispatchEvent(new CustomEvent("open-transfer")),
        leftSection: <ArrowLeftRightIcon size={24} />,
      },
    ],
  },
  {
    group: "Account",
    actions: [
      {
        id: "account",
        label: "Your Account",
        description: "View and manage your account details",
        keywords: [
          "profile",
          "settings",
          "preferences",
          "user info",
          "my details",
          "personal information",
        ],
        onClick: () => window.dispatchEvent(new CustomEvent("open-account")),
        leftSection: <UserIcon size={24} />,
      },
      {
        id: "feedback",
        label: "Share Feedback",
        description: "Let us know how we can improve",
        keywords: [
          "suggestions",
          "report bug",
          "help",
          "contact us",
          "feature request",
          "complaint",
        ],
        onClick: () => window.dispatchEvent(new CustomEvent("open-feedback")),
        leftSection: <PencilEdit01Icon size={24} />,
      },
      {
        id: "support",
        label: "Support",
        description: "Get help and support",
        keywords: [
          "contact us",
          "customer service",
          "faq",
          "documentation",
          "help center",
          "assistance",
        ],
        onClick: () => console.log("Support action triggered"),
        leftSection: <Message01Icon size={24} />,
      },
      {
        id: "logout",
        label: "Logout",
        description: "Sign out of your account",
        keywords: [
          "sign out",
          "exit",
          "quit",
          "log out",
          "end session",
          "leave",
        ],
        onClick: logout,
        leftSection: <Logout02Icon size={24} />,
      },
    ],
  },
];
