import { Contact, ContactType } from "@/features/contacts/types/contact";

export const mockContacts: Contact[] = [
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
    contactType: ContactType.Business,
    business_name: "Layton Construction",
    email: "contact@layton.com",
    phone_number: "(512) 555-0101",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12",
    contactType: ContactType.Business,
    business_name: "J2 Homes",
    email: "contact@j2homes.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13",
    contactType: ContactType.Business,
    business_name: "Wasatch Drywall",
    email: "office@wasatchdrywall.co",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14",
    contactType: ContactType.Business,
    business_name: "Urban Alfandre",
    email: "info@urbanalfandre.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15",
    contactType: ContactType.Business,
    business_name: "Slate Plumbing",
    email: "contact@slateplumbing.com",
    phone_number: "(512) 555-0102",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16",
    contactType: ContactType.Business,
    business_name: "Midway Painting Co",
    email: "contact@midwaypainting.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17",
    contactType: ContactType.Business,
    business_name: "Frontier Building Co",
    email: "accounts@frontierbuilding.inc",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18",
    contactType: ContactType.Business,
    business_name: "Ezra Lee Design",
    email: "contact@ezralee.com",
    phone_number: "(512) 555-0103",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19",
    contactType: ContactType.Business,
    business_name: "Cascade Siding",
    email: "contact@cascadesiding.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20",
    contactType: ContactType.Business,
    business_name: "Kings Mountain Builders",
    email: "info@kingsmountain.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a21",
    contactType: ContactType.Business,
    business_name: "Edge Home",
    email: "contact@edgehome.com",
    phone_number: "",
    avatar_url: "",
  },
];
