import { Contact } from "@/features/contacts/types/contact";

export const mockContacts: Contact[] = [
  {
    id: "1",
    full_name: "Layton Construction",
    email: "contact@layton.com",
    phone_number: "(512) 555-0101",
    avatar_url: "",
    topContact: true,
  },
  {
    id: "2",
    full_name: "J2 Homes",
    email: "contact@j2homes.com",
    phone_number: "",
    avatar_url: "",
    topContact: true,
  },
  {
    id: "3",
    full_name: "Wasatch Drywall",
    email: "office@wasatchdrywall.co",
    phone_number: "",
    avatar_url: "",
    topContact: true,
  },
  {
    id: "4",
    full_name: "Urban Alfandre",
    email: "info@urbanalfandre.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "5",
    full_name: "Slate Plumbing",
    email: "contact@slateplumbing.com",
    phone_number: "(512) 555-0102",
    avatar_url: "",
  },
  {
    id: "6",
    full_name: "Midway Painting Co",
    email: "contact@midwaypainting.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "7",
    full_name: "Frontier Building Co",
    email: "accounts@frontierbuilding.inc",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "8",
    full_name: "Ezra Lee Design",
    email: "contact@ezralee.com",
    phone_number: "(512) 555-0103",
    avatar_url: "",
  },
  {
    id: "9",
    full_name: "Cascade Siding",
    email: "contact@cascadesiding.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "10",
    full_name: "Kings Mountain Builders",
    email: "info@kingsmountain.com",
    phone_number: "",
    avatar_url: "",
  },
  {
    id: "11",
    full_name: "Edge Home",
    email: "contact@edgehome.com",
    phone_number: "",
    avatar_url: "",
  },
];
