import { Transaction } from "@/types/transaction";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    amount: 5.63,
    date: "2025-08-24T10:15:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Starbucks",
    bankAccount: "Chase Checking",
    avatar: "SB",
  },
  {
    id: "2",
    amount: 1250.0,
    date: "2025-08-23T15:30:00Z",
    status: "Completed",
    type: "Received",
    sender: "Client Inc.",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "CI",
  },
  {
    id: "3",
    amount: 85.2,
    date: "2025-08-22T08:45:00Z",
    status: "Pending",
    type: "Sent",
    sender: "You",
    receiver: "Amazon",
    bankAccount: "Chase Checking",
    avatar: "AM",
  },
  {
    id: "4",
    amount: 500.0,
    date: "2025-08-21T18:00:00Z",
    status: "Completed",
    type: "Deposited",
    sender: "Stripe",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "ST",
  },
  {
    id: "6",
    amount: 42.11,
    date: "2025-08-19T09:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "H-E-B",
    bankAccount: "Chase Checking",
    avatar: "HEB",
  },
];
