import { Transaction } from "@/types/transaction";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    amount: 15750.55,
    date: "2025-08-24T10:15:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Layton Construction",
    bankAccount: "Chase Checking",
    avatar: "LC",
  },
  {
    id: "2",
    amount: 185200.0,
    date: "2025-08-23T15:30:00Z",
    status: "Completed",
    type: "Received",
    sender: "J2 Homes",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "J2",
  },
  {
    id: "3",
    amount: 45300.2,
    date: "2025-08-22T08:45:00Z",
    status: "Pending",
    type: "Sent",
    sender: "You",
    receiver: "Wasatch Drywall",
    bankAccount: "Chase Checking",
    avatar: "WD",
  },
  {
    id: "4",
    amount: 98500.0,
    date: "2025-08-21T18:00:00Z",
    status: "Completed",
    type: "Deposited",
    sender: "Stripe",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "ST",
  },
  {
    id: "5",
    amount: 112000.0,
    date: "2025-08-20T11:00:00Z",
    status: "Completed",
    type: "Received",
    sender: "Urban Alfandre",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "UA",
  },
  {
    id: "6",
    amount: 22450.75,
    date: "2025-08-19T09:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Slate Plumbing",
    bankAccount: "Chase Checking",
    avatar: "SP",
  },
  {
    id: "7",
    amount: 78000.0,
    date: "2025-08-18T14:20:00Z",
    status: "Pending",
    type: "Sent",
    sender: "You",
    receiver: "Midway Painting Co",
    bankAccount: "Chase Checking",
    avatar: "MP",
  },
  {
    id: "8",
    amount: 18500.0,
    date: "2025-08-17T16:50:00Z",
    status: "Failed",
    type: "Sent",
    sender: "You",
    receiver: "Frontier Building Co",
    bankAccount: "Chase Checking",
    avatar: "FB",
  },
  {
    id: "9",
    amount: 150000.0,
    date: "2025-08-16T10:00:00Z",
    status: "Completed",
    type: "Transferred",
    sender: "You",
    receiver: "Business Savings",
    bankAccount: "Chase Checking",
    avatar: "MV",
  },
  {
    id: "10",
    amount: 195500.0,
    date: "2025-08-15T13:00:00Z",
    status: "Completed",
    type: "Received",
    sender: "Ezra Lee Design",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "EL",
  },
  {
    id: "11",
    amount: 68500.0,
    date: "2025-08-14T09:30:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Cascade Siding",
    bankAccount: "Chase Checking",
    avatar: "CS",
  },
  {
    id: "12",
    amount: 32150.5,
    date: "2025-08-13T12:15:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Kings Mountain Builders",
    bankAccount: "Chase Checking",
    avatar: "KM",
  },
  {
    id: "13",
    amount: 165000.0,
    date: "2025-08-12T17:00:00Z",
    status: "Pending",
    type: "Received",
    sender: "Edge Home",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "EH",
  },
  {
    id: "14",
    amount: 29800.0,
    date: "2025-08-11T08:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Layton Construction",
    bankAccount: "Chase Checking",
    avatar: "LC",
  },
  {
    id: "15",
    amount: 147300.0,
    date: "2025-08-10T11:45:00Z",
    status: "Completed",
    type: "Received",
    sender: "J2 Homes",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "J2",
  },
  {
    id: "16",
    amount: 55000.0,
    date: "2025-08-09T14:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Slate Plumbing",
    bankAccount: "Chase Checking",
    avatar: "SP",
  },
  {
    id: "17",
    amount: 88750.25,
    date: "2025-08-08T16:20:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Frontier Building Co",
    bankAccount: "Chase Checking",
    avatar: "FB",
  },
  {
    id: "18",
    amount: 85000.0,
    date: "2025-08-07T10:10:00Z",
    status: "Failed",
    type: "Received",
    sender: "Wasatch Drywall",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "WD",
  },
  {
    id: "19",
    amount: 198000.0,
    date: "2025-08-06T12:00:00Z",
    status: "Completed",
    type: "Deposited",
    sender: "Client Payment",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "CP",
  },
  {
    id: "20",
    amount: 135000.0,
    date: "2025-08-05T15:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Urban Alfandre",
    bankAccount: "Chase Checking",
    avatar: "UA",
  },
];
