import { Transaction } from "@/types/transaction";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    amount: 5.63,
    date: "2025-08-24T10:15:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Starbucks",
    bankAccount: "Chase Checking",
    avatar: "SB",
  },
  {
    id: "2",
    amount: 1250.0,
    date: "2025-08-23T15:30:00Z",
    status: "Completed",
    type: "Received",
    sender: "Keystone Construction",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "KC",
  },
  {
    id: "3",
    amount: 85.2,
    date: "2025-08-22T08:45:00Z",
    status: "Pending",
    type: "Sent",
    sender: "You",
    receiver: "The Home Depot",
    bankAccount: "Chase Checking",
    avatar: "HD",
  },
  {
    id: "4",
    amount: 500.0,
    date: "2025-08-21T18:00:00Z",
    status: "Completed",
    type: "Deposited",
    sender: "Stripe",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "ST",
  },
  {
    id: "5",
    amount: 3200.0,
    date: "2025-08-20T11:00:00Z",
    status: "Completed",
    type: "Received",
    sender: "Apex General Contracting",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "AG",
  },
  {
    id: "6",
    amount: 42.11,
    date: "2025-08-19T09:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "H-E-B",
    bankAccount: "Chase Checking",
    avatar: "HE",
  },
  {
    id: "7",
    amount: 750.0,
    date: "2025-08-18T14:20:00Z",
    status: "Pending",
    type: "Sent",
    sender: "You",
    receiver: "Bolt Electric",
    bankAccount: "Chase Checking",
    avatar: "BE",
  },
  {
    id: "8",
    amount: 150.0,
    date: "2025-08-17T16:50:00Z",
    status: "Failed",
    type: "Sent",
    sender: "You",
    receiver: "Lowe's",
    bankAccount: "Chase Checking",
    avatar: "LO",
  },
  {
    id: "9",
    amount: 5000.0,
    date: "2025-08-16T10:00:00Z",
    status: "Completed",
    type: "Transferred",
    sender: "You",
    receiver: "Business Savings",
    bankAccount: "Chase Checking",
    avatar: "MV",
  },
  {
    id: "10",
    amount: 2500.0,
    date: "2025-08-15T13:00:00Z",
    status: "Completed",
    type: "Received",
    sender: "Pinnacle Homes",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "PH",
  },
  {
    id: "11",
    amount: 680.0,
    date: "2025-08-14T09:30:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Solid Foundation Inc.",
    bankAccount: "Chase Checking",
    avatar: "SF",
  },
  {
    id: "12",
    amount: 120.5,
    date: "2025-08-13T12:15:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Sunbelt Rentals",
    bankAccount: "Chase Checking",
    avatar: "SR",
  },
  {
    id: "13",
    amount: 1800.0,
    date: "2025-08-12T17:00:00Z",
    status: "Pending",
    type: "Received",
    sender: "Terra Firma Excavation",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "TF",
  },
  {
    id: "14",
    amount: 95.0,
    date: "2025-08-11T08:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "United Rentals",
    bankAccount: "Chase Checking",
    avatar: "UR",
  },
  {
    id: "15",
    amount: 4500.0,
    date: "2025-08-10T11:45:00Z",
    status: "Completed",
    type: "Received",
    sender: "Skyline Crane & Rigging",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "SC",
  },
  {
    id: "16",
    amount: 300.0,
    date: "2025-08-09T14:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Precision Plumbing Co.",
    bankAccount: "Chase Checking",
    avatar: "PP",
  },
  {
    id: "17",
    amount: 220.75,
    date: "2025-08-08T16:20:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Builders FirstSource",
    bankAccount: "Chase Checking",
    avatar: "BF",
  },
  {
    id: "18",
    amount: 850.0,
    date: "2025-08-07T10:10:00Z",
    status: "Failed",
    type: "Received",
    sender: "Meridian Drywall",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "MD",
  },
  {
    id: "19",
    amount: 10000.0,
    date: "2025-08-06T12:00:00Z",
    status: "Completed",
    type: "Deposited",
    sender: "Client Payment",
    receiver: "You",
    bankAccount: "Business Savings",
    avatar: "CP",
  },
  {
    id: "20",
    amount: 1250.0,
    date: "2025-08-05T15:00:00Z",
    status: "Completed",
    type: "Sent",
    sender: "You",
    receiver: "Castlestone Masonry",
    bankAccount: "Chase Checking",
    avatar: "CM",
  },
];
